/* desmarcar */if(top.location!=self.location){top.location.replace(self.location);}
/* console */(function(){var method;var noop=function(){};var methods=['assert','clear','count','debug','dir','dirxml','error','exception','group','groupCollapsed','groupEnd','info','log','markTimeline','profile','profileEnd','table','time','timeEnd','timeStamp','trace','warn'];var length=methods.length;var console=(window.console=window.console||{});while(length--){method=methods[length];if(!console[method]){console[method]=noop;}}})();
/* site-jquery-ui/jquery-ui */(function(factory){"use strict";if(typeof define==="function"&&define.amd){define(["jquery"],factory);}else{factory(jQuery);}})(function($){"use strict";$.ui=$.ui||{};var version=$.ui.version="1.13.2";var widgetUuid=0;var widgetHasOwnProperty=Array.prototype.hasOwnProperty;var widgetSlice=Array.prototype.slice;$.cleanData=(function(orig){return function(elems){var events,elem,i;for(i=0;(elem=elems[i])!=null;i++){events=$._data(elem,"events");if(events&&events.remove){$(elem).triggerHandler("remove");}}
orig(elems);};})($.cleanData);$.widget=function(name,base,prototype){var existingConstructor,constructor,basePrototype;var proxiedPrototype={};var namespace=name.split(".")[0];name=name.split(".")[1];var fullName=namespace+"-"+name;if(!prototype){prototype=base;base=$.Widget;}
if(Array.isArray(prototype)){prototype=$.extend.apply(null,[{}].concat(prototype));}
$.expr.pseudos[fullName.toLowerCase()]=function(elem){return!!$.data(elem,fullName);};$[namespace]=$[namespace]||{};existingConstructor=$[namespace][name];constructor=$[namespace][name]=function(options,element){if(!this||!this._createWidget){return new constructor(options,element);}
if(arguments.length){this._createWidget(options,element);}};$.extend(constructor,existingConstructor,{version:prototype.version,_proto:$.extend({},prototype),_childConstructors:[]});basePrototype=new base();basePrototype.options=$.widget.extend({},basePrototype.options);$.each(prototype,function(prop,value){if(typeof value!=="function"){proxiedPrototype[prop]=value;return;}
proxiedPrototype[prop]=(function(){function _super(){return base.prototype[prop].apply(this,arguments);}
function _superApply(args){return base.prototype[prop].apply(this,args);}
return function(){var __super=this._super;var __superApply=this._superApply;var returnValue;this._super=_super;this._superApply=_superApply;returnValue=value.apply(this,arguments);this._super=__super;this._superApply=__superApply;return returnValue;};})();});constructor.prototype=$.widget.extend(basePrototype,{widgetEventPrefix:existingConstructor?(basePrototype.widgetEventPrefix||name):name},proxiedPrototype,{constructor:constructor,namespace:namespace,widgetName:name,widgetFullName:fullName});if(existingConstructor){$.each(existingConstructor._childConstructors,function(i,child){var childPrototype=child.prototype;$.widget(childPrototype.namespace+"."+childPrototype.widgetName,constructor,child._proto);});delete existingConstructor._childConstructors;}else{base._childConstructors.push(constructor);}
$.widget.bridge(name,constructor);return constructor;};$.widget.extend=function(target){var input=widgetSlice.call(arguments,1);var inputIndex=0;var inputLength=input.length;var key;var value;for(;inputIndex<inputLength;inputIndex++){for(key in input[inputIndex]){value=input[inputIndex][key];if(widgetHasOwnProperty.call(input[inputIndex],key)&&value!==undefined){if($.isPlainObject(value)){target[key]=$.isPlainObject(target[key])?$.widget.extend({},target[key],value):$.widget.extend({},value);}else{target[key]=value;}}}}
return target;};$.widget.bridge=function(name,object){var fullName=object.prototype.widgetFullName||name;$.fn[name]=function(options){var isMethodCall=typeof options==="string";var args=widgetSlice.call(arguments,1);var returnValue=this;if(isMethodCall){if(!this.length&&options==="instance"){returnValue=undefined;}else{this.each(function(){var methodValue;var instance=$.data(this,fullName);if(options==="instance"){returnValue=instance;return false;}
if(!instance){return $.error("cannot call methods on "+name+" prior to initialization; "+"attempted to call method '"+options+"'");}
if(typeof instance[options]!=="function"||options.charAt(0)==="_"){return $.error("no such method '"+options+"' for "+name+" widget instance");}
methodValue=instance[options].apply(instance,args);if(methodValue!==instance&&methodValue!==undefined){returnValue=methodValue&&methodValue.jquery?returnValue.pushStack(methodValue.get()):methodValue;return false;}});}}else{if(args.length){options=$.widget.extend.apply(null,[options].concat(args));}
this.each(function(){var instance=$.data(this,fullName);if(instance){instance.option(options||{});if(instance._init){instance._init();}}else{$.data(this,fullName,new object(options,this));}});}
return returnValue;};};$.Widget=function(){};$.Widget._childConstructors=[];$.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",defaultElement:"<div>",options:{classes:{},disabled:false,create:null},_createWidget:function(options,element){element=$(element||this.defaultElement||this)[0];this.element=$(element);this.uuid=widgetUuid++;this.eventNamespace="."+this.widgetName+this.uuid;this.bindings=$();this.hoverable=$();this.focusable=$();this.classesElementLookup={};if(element!==this){$.data(element,this.widgetFullName,this);this._on(true,this.element,{remove:function(event){if(event.target===element){this.destroy();}}});this.document=$(element.style?element.ownerDocument:element.document||element);this.window=$(this.document[0].defaultView||this.document[0].parentWindow);}
this.options=$.widget.extend({},this.options,this._getCreateOptions(),options);this._create();if(this.options.disabled){this._setOptionDisabled(this.options.disabled);}
this._trigger("create",null,this._getCreateEventData());this._init();},_getCreateOptions:function(){return{};},_getCreateEventData:$.noop,_create:$.noop,_init:$.noop,destroy:function(){var that=this;this._destroy();$.each(this.classesElementLookup,function(key,value){that._removeClass(value,key);});this.element.off(this.eventNamespace).removeData(this.widgetFullName);this.widget().off(this.eventNamespace).removeAttr("aria-disabled");this.bindings.off(this.eventNamespace);},_destroy:$.noop,widget:function(){return this.element;},option:function(key,value){var options=key;var parts;var curOption;var i;if(arguments.length===0){return $.widget.extend({},this.options);}
if(typeof key==="string"){options={};parts=key.split(".");key=parts.shift();if(parts.length){curOption=options[key]=$.widget.extend({},this.options[key]);for(i=0;i<parts.length-1;i++){curOption[parts[i]]=curOption[parts[i]]||{};curOption=curOption[parts[i]];}
key=parts.pop();if(arguments.length===1){return curOption[key]===undefined?null:curOption[key];}
curOption[key]=value;}else{if(arguments.length===1){return this.options[key]===undefined?null:this.options[key];}
options[key]=value;}}
this._setOptions(options);return this;},_setOptions:function(options){var key;for(key in options){this._setOption(key,options[key]);}
return this;},_setOption:function(key,value){if(key==="classes"){this._setOptionClasses(value);}
this.options[key]=value;if(key==="disabled"){this._setOptionDisabled(value);}
return this;},_setOptionClasses:function(value){var classKey,elements,currentElements;for(classKey in value){currentElements=this.classesElementLookup[classKey];if(value[classKey]===this.options.classes[classKey]||!currentElements||!currentElements.length){continue;}
elements=$(currentElements.get());this._removeClass(currentElements,classKey);elements.addClass(this._classes({element:elements,keys:classKey,classes:value,add:true}));}},_setOptionDisabled:function(value){this._toggleClass(this.widget(),this.widgetFullName+"-disabled",null,!!value);if(value){this._removeClass(this.hoverable,null,"ui-state-hover");this._removeClass(this.focusable,null,"ui-state-focus");}},enable:function(){return this._setOptions({disabled:false});},disable:function(){return this._setOptions({disabled:true});},_classes:function(options){var full=[];var that=this;options=$.extend({element:this.element,classes:this.options.classes||{}},options);function bindRemoveEvent(){var nodesToBind=[];options.element.each(function(_,element){var isTracked=$.map(that.classesElementLookup,function(elements){return elements;}).some(function(elements){return elements.is(element);});if(!isTracked){nodesToBind.push(element);}});that._on($(nodesToBind),{remove:"_untrackClassesElement"});}
function processClassString(classes,checkOption){var current,i;for(i=0;i<classes.length;i++){current=that.classesElementLookup[classes[i]]||$();if(options.add){bindRemoveEvent();current=$($.uniqueSort(current.get().concat(options.element.get())));}else{current=$(current.not(options.element).get());}
that.classesElementLookup[classes[i]]=current;full.push(classes[i]);if(checkOption&&options.classes[classes[i]]){full.push(options.classes[classes[i]]);}}}
if(options.keys){processClassString(options.keys.match(/\S+/g)||[],true);}
if(options.extra){processClassString(options.extra.match(/\S+/g)||[]);}
return full.join(" ");},_untrackClassesElement:function(event){var that=this;$.each(that.classesElementLookup,function(key,value){if($.inArray(event.target,value)!==-1){that.classesElementLookup[key]=$(value.not(event.target).get());}});this._off($(event.target));},_removeClass:function(element,keys,extra){return this._toggleClass(element,keys,extra,false);},_addClass:function(element,keys,extra){return this._toggleClass(element,keys,extra,true);},_toggleClass:function(element,keys,extra,add){add=(typeof add==="boolean")?add:extra;var shift=(typeof element==="string"||element===null),options={extra:shift?keys:extra,keys:shift?element:keys,element:shift?this.element:element,add:add};options.element.toggleClass(this._classes(options),add);return this;},_on:function(suppressDisabledCheck,element,handlers){var delegateElement;var instance=this;if(typeof suppressDisabledCheck!=="boolean"){handlers=element;element=suppressDisabledCheck;suppressDisabledCheck=false;}
if(!handlers){handlers=element;element=this.element;delegateElement=this.widget();}else{element=delegateElement=$(element);this.bindings=this.bindings.add(element);}
$.each(handlers,function(event,handler){function handlerProxy(){if(!suppressDisabledCheck&&(instance.options.disabled===true||$(this).hasClass("ui-state-disabled"))){return;}
return(typeof handler==="string"?instance[handler]:handler).apply(instance,arguments);}
if(typeof handler!=="string"){handlerProxy.guid=handler.guid=handler.guid||handlerProxy.guid||$.guid++;}
var match=event.match(/^([\w:-]*)\s*(.*)$/);var eventName=match[1]+instance.eventNamespace;var selector=match[2];if(selector){delegateElement.on(eventName,selector,handlerProxy);}else{element.on(eventName,handlerProxy);}});},_off:function(element,eventName){eventName=(eventName||"").split(" ").join(this.eventNamespace+" ")+
this.eventNamespace;element.off(eventName);this.bindings=$(this.bindings.not(element).get());this.focusable=$(this.focusable.not(element).get());this.hoverable=$(this.hoverable.not(element).get());},_delay:function(handler,delay){function handlerProxy(){return(typeof handler==="string"?instance[handler]:handler).apply(instance,arguments);}
var instance=this;return setTimeout(handlerProxy,delay||0);},_hoverable:function(element){this.hoverable=this.hoverable.add(element);this._on(element,{mouseenter:function(event){this._addClass($(event.currentTarget),null,"ui-state-hover");},mouseleave:function(event){this._removeClass($(event.currentTarget),null,"ui-state-hover");}});},_focusable:function(element){this.focusable=this.focusable.add(element);this._on(element,{focusin:function(event){this._addClass($(event.currentTarget),null,"ui-state-focus");},focusout:function(event){this._removeClass($(event.currentTarget),null,"ui-state-focus");}});},_trigger:function(type,event,data){var prop,orig;var callback=this.options[type];data=data||{};event=$.Event(event);event.type=(type===this.widgetEventPrefix?type:this.widgetEventPrefix+type).toLowerCase();event.target=this.element[0];orig=event.originalEvent;if(orig){for(prop in orig){if(!(prop in event)){event[prop]=orig[prop];}}}
this.element.trigger(event,data);return!(typeof callback==="function"&&callback.apply(this.element[0],[event].concat(data))===false||event.isDefaultPrevented());}};$.each({show:"fadeIn",hide:"fadeOut"},function(method,defaultEffect){$.Widget.prototype["_"+method]=function(element,options,callback){if(typeof options==="string"){options={effect:options};}
var hasOptions;var effectName=!options?method:options===true||typeof options==="number"?defaultEffect:options.effect||defaultEffect;options=options||{};if(typeof options==="number"){options={duration:options};}else if(options===true){options={};}
hasOptions=!$.isEmptyObject(options);options.complete=callback;if(options.delay){element.delay(options.delay);}
if(hasOptions&&$.effects&&$.effects.effect[effectName]){element[method](options);}else if(effectName!==method&&element[effectName]){element[effectName](options.duration,options.easing,callback);}else{element.queue(function(next){$(this)[method]();if(callback){callback.call(element[0]);}
next();});}};});var widget=$.widget;(function(){var cachedScrollbarWidth,max=Math.max,abs=Math.abs,rhorizontal=/left|center|right/,rvertical=/top|center|bottom/,roffset=/[\+\-]\d+(\.[\d]+)?%?/,rposition=/^\w+/,rpercent=/%$/,_position=$.fn.position;function getOffsets(offsets,width,height){return[parseFloat(offsets[0])*(rpercent.test(offsets[0])?width / 100:1),parseFloat(offsets[1])*(rpercent.test(offsets[1])?height / 100:1)];}
function parseCss(element,property){return parseInt($.css(element,property),10)||0;}
function isWindow(obj){return obj!=null&&obj===obj.window;}
function getDimensions(elem){var raw=elem[0];if(raw.nodeType===9){return{width:elem.width(),height:elem.height(),offset:{top:0,left:0}};}
if(isWindow(raw)){return{width:elem.width(),height:elem.height(),offset:{top:elem.scrollTop(),left:elem.scrollLeft()}};}
if(raw.preventDefault){return{width:0,height:0,offset:{top:raw.pageY,left:raw.pageX}};}
return{width:elem.outerWidth(),height:elem.outerHeight(),offset:elem.offset()};}
$.position={scrollbarWidth:function(){if(cachedScrollbarWidth!==undefined){return cachedScrollbarWidth;}
var w1,w2,div=$("<div style="+"'display:block;position:absolute;width:200px;height:200px;overflow:hidden;'>"+"<div style='height:300px;width:auto;'></div></div>"),innerDiv=div.children()[0];$("body").append(div);w1=innerDiv.offsetWidth;div.css("overflow","scroll");w2=innerDiv.offsetWidth;if(w1===w2){w2=div[0].clientWidth;}
div.remove();return(cachedScrollbarWidth=w1-w2);},getScrollInfo:function(within){var overflowX=within.isWindow||within.isDocument?"":within.element.css("overflow-x"),overflowY=within.isWindow||within.isDocument?"":within.element.css("overflow-y"),hasOverflowX=overflowX==="scroll"||(overflowX==="auto"&&within.width<within.element[0].scrollWidth),hasOverflowY=overflowY==="scroll"||(overflowY==="auto"&&within.height<within.element[0].scrollHeight);return{width:hasOverflowY?$.position.scrollbarWidth():0,height:hasOverflowX?$.position.scrollbarWidth():0};},getWithinInfo:function(element){var withinElement=$(element||window),isElemWindow=isWindow(withinElement[0]),isDocument=!!withinElement[0]&&withinElement[0].nodeType===9,hasOffset=!isElemWindow&&!isDocument;return{element:withinElement,isWindow:isElemWindow,isDocument:isDocument,offset:hasOffset?$(element).offset():{left:0,top:0},scrollLeft:withinElement.scrollLeft(),scrollTop:withinElement.scrollTop(),width:withinElement.outerWidth(),height:withinElement.outerHeight()};}};$.fn.position=function(options){if(!options||!options.of){return _position.apply(this,arguments);}
options=$.extend({},options);var atOffset,targetWidth,targetHeight,targetOffset,basePosition,dimensions,target=typeof options.of==="string"?$(document).find(options.of):$(options.of),within=$.position.getWithinInfo(options.within),scrollInfo=$.position.getScrollInfo(within),collision=(options.collision||"flip").split(" "),offsets={};dimensions=getDimensions(target);if(target[0].preventDefault){options.at="left top";}
targetWidth=dimensions.width;targetHeight=dimensions.height;targetOffset=dimensions.offset;basePosition=$.extend({},targetOffset);$.each(["my","at"],function(){var pos=(options[this]||"").split(" "),horizontalOffset,verticalOffset;if(pos.length===1){pos=rhorizontal.test(pos[0])?pos.concat(["center"]):rvertical.test(pos[0])?["center"].concat(pos):["center","center"];}
pos[0]=rhorizontal.test(pos[0])?pos[0]:"center";pos[1]=rvertical.test(pos[1])?pos[1]:"center";horizontalOffset=roffset.exec(pos[0]);verticalOffset=roffset.exec(pos[1]);offsets[this]=[horizontalOffset?horizontalOffset[0]:0,verticalOffset?verticalOffset[0]:0];options[this]=[rposition.exec(pos[0])[0],rposition.exec(pos[1])[0]];});if(collision.length===1){collision[1]=collision[0];}
if(options.at[0]==="right"){basePosition.left+=targetWidth;}else if(options.at[0]==="center"){basePosition.left+=targetWidth / 2;}
if(options.at[1]==="bottom"){basePosition.top+=targetHeight;}else if(options.at[1]==="center"){basePosition.top+=targetHeight / 2;}
atOffset=getOffsets(offsets.at,targetWidth,targetHeight);basePosition.left+=atOffset[0];basePosition.top+=atOffset[1];return this.each(function(){var collisionPosition,using,elem=$(this),elemWidth=elem.outerWidth(),elemHeight=elem.outerHeight(),marginLeft=parseCss(this,"marginLeft"),marginTop=parseCss(this,"marginTop"),collisionWidth=elemWidth+marginLeft+parseCss(this,"marginRight")+
scrollInfo.width,collisionHeight=elemHeight+marginTop+parseCss(this,"marginBottom")+
scrollInfo.height,position=$.extend({},basePosition),myOffset=getOffsets(offsets.my,elem.outerWidth(),elem.outerHeight());if(options.my[0]==="right"){position.left-=elemWidth;}else if(options.my[0]==="center"){position.left-=elemWidth / 2;}
if(options.my[1]==="bottom"){position.top-=elemHeight;}else if(options.my[1]==="center"){position.top-=elemHeight / 2;}
position.left+=myOffset[0];position.top+=myOffset[1];collisionPosition={marginLeft:marginLeft,marginTop:marginTop};$.each(["left","top"],function(i,dir){if($.ui.position[collision[i]]){$.ui.position[collision[i]][dir](position,{targetWidth:targetWidth,targetHeight:targetHeight,elemWidth:elemWidth,elemHeight:elemHeight,collisionPosition:collisionPosition,collisionWidth:collisionWidth,collisionHeight:collisionHeight,offset:[atOffset[0]+myOffset[0],atOffset[1]+myOffset[1]],my:options.my,at:options.at,within:within,elem:elem});}});if(options.using){using=function(props){var left=targetOffset.left-position.left,right=left+targetWidth-elemWidth,top=targetOffset.top-position.top,bottom=top+targetHeight-elemHeight,feedback={target:{element:target,left:targetOffset.left,top:targetOffset.top,width:targetWidth,height:targetHeight},element:{element:elem,left:position.left,top:position.top,width:elemWidth,height:elemHeight},horizontal:right<0?"left":left>0?"right":"center",vertical:bottom<0?"top":top>0?"bottom":"middle"};if(targetWidth<elemWidth&&abs(left+right)<targetWidth){feedback.horizontal="center";}
if(targetHeight<elemHeight&&abs(top+bottom)<targetHeight){feedback.vertical="middle";}
if(max(abs(left),abs(right))>max(abs(top),abs(bottom))){feedback.important="horizontal";}else{feedback.important="vertical";}
options.using.call(this,props,feedback);};}
elem.offset($.extend(position,{using:using}));});};$.ui.position={fit:{left:function(position,data){var within=data.within,withinOffset=within.isWindow?within.scrollLeft:within.offset.left,outerWidth=within.width,collisionPosLeft=position.left-data.collisionPosition.marginLeft,overLeft=withinOffset-collisionPosLeft,overRight=collisionPosLeft+data.collisionWidth-outerWidth-withinOffset,newOverRight;if(data.collisionWidth>outerWidth){if(overLeft>0&&overRight<=0){newOverRight=position.left+overLeft+data.collisionWidth-outerWidth-
withinOffset;position.left+=overLeft-newOverRight;}else if(overRight>0&&overLeft<=0){position.left=withinOffset;}else{if(overLeft>overRight){position.left=withinOffset+outerWidth-data.collisionWidth;}else{position.left=withinOffset;}}}else if(overLeft>0){position.left+=overLeft;}else if(overRight>0){position.left-=overRight;}else{position.left=max(position.left-collisionPosLeft,position.left);}},top:function(position,data){var within=data.within,withinOffset=within.isWindow?within.scrollTop:within.offset.top,outerHeight=data.within.height,collisionPosTop=position.top-data.collisionPosition.marginTop,overTop=withinOffset-collisionPosTop,overBottom=collisionPosTop+data.collisionHeight-outerHeight-withinOffset,newOverBottom;if(data.collisionHeight>outerHeight){if(overTop>0&&overBottom<=0){newOverBottom=position.top+overTop+data.collisionHeight-outerHeight-
withinOffset;position.top+=overTop-newOverBottom;}else if(overBottom>0&&overTop<=0){position.top=withinOffset;}else{if(overTop>overBottom){position.top=withinOffset+outerHeight-data.collisionHeight;}else{position.top=withinOffset;}}}else if(overTop>0){position.top+=overTop;}else if(overBottom>0){position.top-=overBottom;}else{position.top=max(position.top-collisionPosTop,position.top);}}},flip:{left:function(position,data){var within=data.within,withinOffset=within.offset.left+within.scrollLeft,outerWidth=within.width,offsetLeft=within.isWindow?within.scrollLeft:within.offset.left,collisionPosLeft=position.left-data.collisionPosition.marginLeft,overLeft=collisionPosLeft-offsetLeft,overRight=collisionPosLeft+data.collisionWidth-outerWidth-offsetLeft,myOffset=data.my[0]==="left"?-data.elemWidth:data.my[0]==="right"?data.elemWidth:0,atOffset=data.at[0]==="left"?data.targetWidth:data.at[0]==="right"?-data.targetWidth:0,offset=-2*data.offset[0],newOverRight,newOverLeft;if(overLeft<0){newOverRight=position.left+myOffset+atOffset+offset+data.collisionWidth-
outerWidth-withinOffset;if(newOverRight<0||newOverRight<abs(overLeft)){position.left+=myOffset+atOffset+offset;}}else if(overRight>0){newOverLeft=position.left-data.collisionPosition.marginLeft+myOffset+
atOffset+offset-offsetLeft;if(newOverLeft>0||abs(newOverLeft)<overRight){position.left+=myOffset+atOffset+offset;}}},top:function(position,data){var within=data.within,withinOffset=within.offset.top+within.scrollTop,outerHeight=within.height,offsetTop=within.isWindow?within.scrollTop:within.offset.top,collisionPosTop=position.top-data.collisionPosition.marginTop,overTop=collisionPosTop-offsetTop,overBottom=collisionPosTop+data.collisionHeight-outerHeight-offsetTop,top=data.my[1]==="top",myOffset=top?-data.elemHeight:data.my[1]==="bottom"?data.elemHeight:0,atOffset=data.at[1]==="top"?data.targetHeight:data.at[1]==="bottom"?-data.targetHeight:0,offset=-2*data.offset[1],newOverTop,newOverBottom;if(overTop<0){newOverBottom=position.top+myOffset+atOffset+offset+data.collisionHeight-
outerHeight-withinOffset;if(newOverBottom<0||newOverBottom<abs(overTop)){position.top+=myOffset+atOffset+offset;}}else if(overBottom>0){newOverTop=position.top-data.collisionPosition.marginTop+myOffset+atOffset+
offset-offsetTop;if(newOverTop>0||abs(newOverTop)<overBottom){position.top+=myOffset+atOffset+offset;}}}},flipfit:{left:function(){$.ui.position.flip.left.apply(this,arguments);$.ui.position.fit.left.apply(this,arguments);},top:function(){$.ui.position.flip.top.apply(this,arguments);$.ui.position.fit.top.apply(this,arguments);}}};})();var position=$.ui.position;var keycode=$.ui.keyCode={BACKSPACE:8,COMMA:188,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,LEFT:37,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SPACE:32,TAB:9,UP:38};var uniqueId=$.fn.extend({uniqueId:(function(){var uuid=0;return function(){return this.each(function(){if(!this.id){this.id="ui-id-"+(++uuid);}});};})(),removeUniqueId:function(){return this.each(function(){if(/^ui-id-\d+$/.test(this.id)){$(this).removeAttr("id");}});}});var safeActiveElement=$.ui.safeActiveElement=function(document){var activeElement;try{activeElement=document.activeElement;}catch(error){activeElement=document.body;}
if(!activeElement){activeElement=document.body;}
if(!activeElement.nodeName){activeElement=document.body;}
return activeElement;};var widgetsMenu=$.widget("ui.menu",{version:"1.13.2",defaultElement:"<ul>",delay:300,options:{icons:{submenu:"ui-icon-caret-1-e"},items:"> *",menus:"ul",position:{my:"left top",at:"right top"},role:"menu",blur:null,focus:null,select:null},_create:function(){this.activeMenu=this.element;this.mouseHandled=false;this.lastMousePosition={x:null,y:null};this.element.uniqueId().attr({role:this.options.role,tabIndex:0});this._addClass("ui-menu","ui-widget ui-widget-content");this._on({"mousedown .ui-menu-item":function(event){event.preventDefault();this._activateItem(event);},"click .ui-menu-item":function(event){var target=$(event.target);var active=$($.ui.safeActiveElement(this.document[0]));if(!this.mouseHandled&&target.not(".ui-state-disabled").length){this.select(event);if(!event.isPropagationStopped()){this.mouseHandled=true;}
if(target.has(".ui-menu").length){this.expand(event);}else if(!this.element.is(":focus")&&active.closest(".ui-menu").length){this.element.trigger("focus",[true]);if(this.active&&this.active.parents(".ui-menu").length===1){clearTimeout(this.timer);}}}},"mouseenter .ui-menu-item":"_activateItem","mousemove .ui-menu-item":"_activateItem",mouseleave:"collapseAll","mouseleave .ui-menu":"collapseAll",focus:function(event,keepActiveItem){var item=this.active||this._menuItems().first();if(!keepActiveItem){this.focus(event,item);}},blur:function(event){this._delay(function(){var notContained=!$.contains(this.element[0],$.ui.safeActiveElement(this.document[0]));if(notContained){this.collapseAll(event);}});},keydown:"_keydown"});this.refresh();this._on(this.document,{click:function(event){if(this._closeOnDocumentClick(event)){this.collapseAll(event,true);}
this.mouseHandled=false;}});},_activateItem:function(event){if(this.previousFilter){return;}
if(event.clientX===this.lastMousePosition.x&&event.clientY===this.lastMousePosition.y){return;}
this.lastMousePosition={x:event.clientX,y:event.clientY};var actualTarget=$(event.target).closest(".ui-menu-item"),target=$(event.currentTarget);if(actualTarget[0]!==target[0]){return;}
if(target.is(".ui-state-active")){return;}
this._removeClass(target.siblings().children(".ui-state-active"),null,"ui-state-active");this.focus(event,target);},_destroy:function(){var items=this.element.find(".ui-menu-item").removeAttr("role aria-disabled"),submenus=items.children(".ui-menu-item-wrapper").removeUniqueId().removeAttr("tabIndex role aria-haspopup");this.element.removeAttr("aria-activedescendant").find(".ui-menu").addBack().removeAttr("role aria-labelledby aria-expanded aria-hidden aria-disabled "+"tabIndex").removeUniqueId().show();submenus.children().each(function(){var elem=$(this);if(elem.data("ui-menu-submenu-caret")){elem.remove();}});},_keydown:function(event){var match,prev,character,skip,preventDefault=true;switch(event.keyCode){case $.ui.keyCode.PAGE_UP:this.previousPage(event);break;case $.ui.keyCode.PAGE_DOWN:this.nextPage(event);break;case $.ui.keyCode.HOME:this._move("first","first",event);break;case $.ui.keyCode.END:this._move("last","last",event);break;case $.ui.keyCode.UP:this.previous(event);break;case $.ui.keyCode.DOWN:this.next(event);break;case $.ui.keyCode.LEFT:this.collapse(event);break;case $.ui.keyCode.RIGHT:if(this.active&&!this.active.is(".ui-state-disabled")){this.expand(event);}
break;case $.ui.keyCode.ENTER:case $.ui.keyCode.SPACE:this._activate(event);break;case $.ui.keyCode.ESCAPE:this.collapse(event);break;default:preventDefault=false;prev=this.previousFilter||"";skip=false;character=event.keyCode>=96&&event.keyCode<=105?(event.keyCode-96).toString():String.fromCharCode(event.keyCode);clearTimeout(this.filterTimer);if(character===prev){skip=true;}else{character=prev+character;}
match=this._filterMenuItems(character);match=skip&&match.index(this.active.next())!==-1?this.active.nextAll(".ui-menu-item"):match;if(!match.length){character=String.fromCharCode(event.keyCode);match=this._filterMenuItems(character);}
if(match.length){this.focus(event,match);this.previousFilter=character;this.filterTimer=this._delay(function(){delete this.previousFilter;},1000);}else{delete this.previousFilter;}}
if(preventDefault){event.preventDefault();}},_activate:function(event){if(this.active&&!this.active.is(".ui-state-disabled")){if(this.active.children("[aria-haspopup='true']").length){this.expand(event);}else{this.select(event);}}},refresh:function(){var menus,items,newSubmenus,newItems,newWrappers,that=this,icon=this.options.icons.submenu,submenus=this.element.find(this.options.menus);this._toggleClass("ui-menu-icons",null,!!this.element.find(".ui-icon").length);newSubmenus=submenus.filter(":not(.ui-menu)").hide().attr({role:this.options.role,"aria-hidden":"true","aria-expanded":"false"}).each(function(){var menu=$(this),item=menu.prev(),submenuCaret=$("<span>").data("ui-menu-submenu-caret",true);that._addClass(submenuCaret,"ui-menu-icon","ui-icon "+icon);item.attr("aria-haspopup","true").prepend(submenuCaret);menu.attr("aria-labelledby",item.attr("id"));});this._addClass(newSubmenus,"ui-menu","ui-widget ui-widget-content ui-front");menus=submenus.add(this.element);items=menus.find(this.options.items);items.not(".ui-menu-item").each(function(){var item=$(this);if(that._isDivider(item)){that._addClass(item,"ui-menu-divider","ui-widget-content");}});newItems=items.not(".ui-menu-item, .ui-menu-divider");newWrappers=newItems.children().not(".ui-menu").uniqueId().attr({tabIndex:-1,role:this._itemRole()});this._addClass(newItems,"ui-menu-item")._addClass(newWrappers,"ui-menu-item-wrapper");items.filter(".ui-state-disabled").attr("aria-disabled","true");if(this.active&&!$.contains(this.element[0],this.active[0])){this.blur();}},_itemRole:function(){return{menu:"menuitem",listbox:"option"}[this.options.role];},_setOption:function(key,value){if(key==="icons"){var icons=this.element.find(".ui-menu-icon");this._removeClass(icons,null,this.options.icons.submenu)._addClass(icons,null,value.submenu);}
this._super(key,value);},_setOptionDisabled:function(value){this._super(value);this.element.attr("aria-disabled",String(value));this._toggleClass(null,"ui-state-disabled",!!value);},focus:function(event,item){var nested,focused,activeParent;this.blur(event,event&&event.type==="focus");this._scrollIntoView(item);this.active=item.first();focused=this.active.children(".ui-menu-item-wrapper");this._addClass(focused,null,"ui-state-active");if(this.options.role){this.element.attr("aria-activedescendant",focused.attr("id"));}
activeParent=this.active.parent().closest(".ui-menu-item").children(".ui-menu-item-wrapper");this._addClass(activeParent,null,"ui-state-active");if(event&&event.type==="keydown"){this._close();}else{this.timer=this._delay(function(){this._close();},this.delay);}
nested=item.children(".ui-menu");if(nested.length&&event&&(/^mouse/.test(event.type))){this._startOpening(nested);}
this.activeMenu=item.parent();this._trigger("focus",event,{item:item});},_scrollIntoView:function(item){var borderTop,paddingTop,offset,scroll,elementHeight,itemHeight;if(this._hasScroll()){borderTop=parseFloat($.css(this.activeMenu[0],"borderTopWidth"))||0;paddingTop=parseFloat($.css(this.activeMenu[0],"paddingTop"))||0;offset=item.offset().top-this.activeMenu.offset().top-borderTop-paddingTop;scroll=this.activeMenu.scrollTop();elementHeight=this.activeMenu.height();itemHeight=item.outerHeight();if(offset<0){this.activeMenu.scrollTop(scroll+offset);}else if(offset+itemHeight>elementHeight){this.activeMenu.scrollTop(scroll+offset-elementHeight+itemHeight);}}},blur:function(event,fromFocus){if(!fromFocus){clearTimeout(this.timer);}
if(!this.active){return;}
this._removeClass(this.active.children(".ui-menu-item-wrapper"),null,"ui-state-active");this._trigger("blur",event,{item:this.active});this.active=null;},_startOpening:function(submenu){clearTimeout(this.timer);if(submenu.attr("aria-hidden")!=="true"){return;}
this.timer=this._delay(function(){this._close();this._open(submenu);},this.delay);},_open:function(submenu){var position=$.extend({of:this.active},this.options.position);clearTimeout(this.timer);this.element.find(".ui-menu").not(submenu.parents(".ui-menu")).hide().attr("aria-hidden","true");submenu.show().removeAttr("aria-hidden").attr("aria-expanded","true").position(position);},collapseAll:function(event,all){clearTimeout(this.timer);this.timer=this._delay(function(){var currentMenu=all?this.element:$(event&&event.target).closest(this.element.find(".ui-menu"));if(!currentMenu.length){currentMenu=this.element;}
this._close(currentMenu);this.blur(event);this._removeClass(currentMenu.find(".ui-state-active"),null,"ui-state-active");this.activeMenu=currentMenu;},all?0:this.delay);},_close:function(startMenu){if(!startMenu){startMenu=this.active?this.active.parent():this.element;}
startMenu.find(".ui-menu").hide().attr("aria-hidden","true").attr("aria-expanded","false");},_closeOnDocumentClick:function(event){return!$(event.target).closest(".ui-menu").length;},_isDivider:function(item){return!/[^\-\u2014\u2013\s]/.test(item.text());},collapse:function(event){var newItem=this.active&&this.active.parent().closest(".ui-menu-item",this.element);if(newItem&&newItem.length){this._close();this.focus(event,newItem);}},expand:function(event){var newItem=this.active&&this._menuItems(this.active.children(".ui-menu")).first();if(newItem&&newItem.length){this._open(newItem.parent());this._delay(function(){this.focus(event,newItem);});}},next:function(event){this._move("next","first",event);},previous:function(event){this._move("prev","last",event);},isFirstItem:function(){return this.active&&!this.active.prevAll(".ui-menu-item").length;},isLastItem:function(){return this.active&&!this.active.nextAll(".ui-menu-item").length;},_menuItems:function(menu){return(menu||this.element).find(this.options.items).filter(".ui-menu-item");},_move:function(direction,filter,event){var next;if(this.active){if(direction==="first"||direction==="last"){next=this.active
[direction==="first"?"prevAll":"nextAll"](".ui-menu-item").last();}else{next=this.active
[direction+"All"](".ui-menu-item").first();}}
if(!next||!next.length||!this.active){next=this._menuItems(this.activeMenu)[filter]();}
this.focus(event,next);},nextPage:function(event){var item,base,height;if(!this.active){this.next(event);return;}
if(this.isLastItem()){return;}
if(this._hasScroll()){base=this.active.offset().top;height=this.element.innerHeight();if($.fn.jquery.indexOf("3.2.")===0){height+=this.element[0].offsetHeight-this.element.outerHeight();}
this.active.nextAll(".ui-menu-item").each(function(){item=$(this);return item.offset().top-base-height<0;});this.focus(event,item);}else{this.focus(event,this._menuItems(this.activeMenu)
[!this.active?"first":"last"]());}},previousPage:function(event){var item,base,height;if(!this.active){this.next(event);return;}
if(this.isFirstItem()){return;}
if(this._hasScroll()){base=this.active.offset().top;height=this.element.innerHeight();if($.fn.jquery.indexOf("3.2.")===0){height+=this.element[0].offsetHeight-this.element.outerHeight();}
this.active.prevAll(".ui-menu-item").each(function(){item=$(this);return item.offset().top-base+height>0;});this.focus(event,item);}else{this.focus(event,this._menuItems(this.activeMenu).first());}},_hasScroll:function(){return this.element.outerHeight()<this.element.prop("scrollHeight");},select:function(event){this.active=this.active||$(event.target).closest(".ui-menu-item");var ui={item:this.active};if(!this.active.has(".ui-menu").length){this.collapseAll(event,true);}
this._trigger("select",event,ui);},_filterMenuItems:function(character){var escapedCharacter=character.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&"),regex=new RegExp("^"+escapedCharacter,"i");return this.activeMenu.find(this.options.items).filter(".ui-menu-item").filter(function(){return regex.test(String.prototype.trim.call($(this).children(".ui-menu-item-wrapper").text()));});}});$.widget("ui.autocomplete",{version:"1.13.2",defaultElement:"<input>",options:{appendTo:null,autoFocus:false,delay:300,minLength:1,position:{my:"left top",at:"left bottom",collision:"none"},source:null,change:null,close:null,focus:null,open:null,response:null,search:null,select:null},requestIndex:0,pending:0,liveRegionTimer:null,_create:function(){var suppressKeyPress,suppressKeyPressRepeat,suppressInput,nodeName=this.element[0].nodeName.toLowerCase(),isTextarea=nodeName==="textarea",isInput=nodeName==="input";this.isMultiLine=isTextarea||!isInput&&this._isContentEditable(this.element);this.valueMethod=this.element[isTextarea||isInput?"val":"text"];this.isNewMenu=true;this._addClass("ui-autocomplete-input");this.element.attr("autocomplete","off");this._on(this.element,{keydown:function(event){if(this.element.prop("readOnly")){suppressKeyPress=true;suppressInput=true;suppressKeyPressRepeat=true;return;}
suppressKeyPress=false;suppressInput=false;suppressKeyPressRepeat=false;var keyCode=$.ui.keyCode;switch(event.keyCode){case keyCode.PAGE_UP:suppressKeyPress=true;this._move("previousPage",event);break;case keyCode.PAGE_DOWN:suppressKeyPress=true;this._move("nextPage",event);break;case keyCode.UP:suppressKeyPress=true;this._keyEvent("previous",event);break;case keyCode.DOWN:suppressKeyPress=true;this._keyEvent("next",event);break;case keyCode.ENTER:if(this.menu.active){suppressKeyPress=true;event.preventDefault();this.menu.select(event);}
break;case keyCode.TAB:if(this.menu.active){this.menu.select(event);}
break;case keyCode.ESCAPE:if(this.menu.element.is(":visible")){if(!this.isMultiLine){this._value(this.term);}
this.close(event);event.preventDefault();}
break;default:suppressKeyPressRepeat=true;this._searchTimeout(event);break;}},keypress:function(event){if(suppressKeyPress){suppressKeyPress=false;if(!this.isMultiLine||this.menu.element.is(":visible")){event.preventDefault();}
return;}
if(suppressKeyPressRepeat){return;}
var keyCode=$.ui.keyCode;switch(event.keyCode){case keyCode.PAGE_UP:this._move("previousPage",event);break;case keyCode.PAGE_DOWN:this._move("nextPage",event);break;case keyCode.UP:this._keyEvent("previous",event);break;case keyCode.DOWN:this._keyEvent("next",event);break;}},input:function(event){if(suppressInput){suppressInput=false;event.preventDefault();return;}
this._searchTimeout(event);},focus:function(){this.selectedItem=null;this.previous=this._value();},blur:function(event){clearTimeout(this.searching);this.close(event);this._change(event);}});this._initSource();this.menu=$("<ul>").appendTo(this._appendTo()).menu({role:null}).hide().attr({"unselectable":"on"}).menu("instance");this._addClass(this.menu.element,"ui-autocomplete","ui-front");this._on(this.menu.element,{mousedown:function(event){event.preventDefault();},menufocus:function(event,ui){var label,item;if(this.isNewMenu){this.isNewMenu=false;if(event.originalEvent&&/^mouse/.test(event.originalEvent.type)){this.menu.blur();this.document.one("mousemove",function(){$(event.target).trigger(event.originalEvent);});return;}}
item=ui.item.data("ui-autocomplete-item");if(false!==this._trigger("focus",event,{item:item})){if(event.originalEvent&&/^key/.test(event.originalEvent.type)){this._value(item.value);}}
label=ui.item.attr("aria-label")||item.value;if(label&&String.prototype.trim.call(label).length){clearTimeout(this.liveRegionTimer);this.liveRegionTimer=this._delay(function(){this.liveRegion.html($("<div>").text(label));},100);}},menuselect:function(event,ui){var item=ui.item.data("ui-autocomplete-item"),previous=this.previous;if(this.element[0]!==$.ui.safeActiveElement(this.document[0])){this.element.trigger("focus");this.previous=previous;this._delay(function(){this.previous=previous;this.selectedItem=item;});}
if(false!==this._trigger("select",event,{item:item})){this._value(item.value);}
this.term=this._value();this.close(event);this.selectedItem=item;}});this.liveRegion=$("<div>",{role:"status","aria-live":"assertive","aria-relevant":"additions"}).appendTo(this.document[0].body);this._addClass(this.liveRegion,null,"ui-helper-hidden-accessible");this._on(this.window,{beforeunload:function(){this.element.removeAttr("autocomplete");}});},_destroy:function(){clearTimeout(this.searching);this.element.removeAttr("autocomplete");this.menu.element.remove();this.liveRegion.remove();},_setOption:function(key,value){this._super(key,value);if(key==="source"){this._initSource();}
if(key==="appendTo"){this.menu.element.appendTo(this._appendTo());}
if(key==="disabled"&&value&&this.xhr){this.xhr.abort();}},_isEventTargetInWidget:function(event){var menuElement=this.menu.element[0];return event.target===this.element[0]||event.target===menuElement||$.contains(menuElement,event.target);},_closeOnClickOutside:function(event){if(!this._isEventTargetInWidget(event)){this.close();}},_appendTo:function(){var element=this.options.appendTo;if(element){element=element.jquery||element.nodeType?$(element):this.document.find(element).eq(0);}
if(!element||!element[0]){element=this.element.closest(".ui-front, dialog");}
if(!element.length){element=this.document[0].body;}
return element;},_initSource:function(){var array,url,that=this;if(Array.isArray(this.options.source)){array=this.options.source;this.source=function(request,response){response($.ui.autocomplete.filter(array,request.term));};}else if(typeof this.options.source==="string"){url=this.options.source;this.source=function(request,response){if(that.xhr){that.xhr.abort();}
that.xhr=$.ajax({url:url,data:request,dataType:"json",success:function(data){response(data);},error:function(){response([]);}});};}else{this.source=this.options.source;}},_searchTimeout:function(event){clearTimeout(this.searching);this.searching=this._delay(function(){var equalValues=this.term===this._value(),menuVisible=this.menu.element.is(":visible"),modifierKey=event.altKey||event.ctrlKey||event.metaKey||event.shiftKey;if(!equalValues||(equalValues&&!menuVisible&&!modifierKey)){this.selectedItem=null;this.search(null,event);}},this.options.delay);},search:function(value,event){value=value!=null?value:this._value();this.term=this._value();if(value.length<this.options.minLength){return this.close(event);}
if(this._trigger("search",event)===false){return;}
return this._search(value);},_search:function(value){this.pending++;this._addClass("ui-autocomplete-loading");this.cancelSearch=false;this.source({term:value},this._response());},_response:function(){var index=++this.requestIndex;return function(content){if(index===this.requestIndex){this.__response(content);}
this.pending--;if(!this.pending){this._removeClass("ui-autocomplete-loading");}}.bind(this);},__response:function(content){if(content){content=this._normalize(content);}
this._trigger("response",null,{content:content});if(!this.options.disabled&&content&&content.length&&!this.cancelSearch){this._suggest(content);this._trigger("open");}else{this._close();}},close:function(event){this.cancelSearch=true;this._close(event);},_close:function(event){this._off(this.document,"mousedown");if(this.menu.element.is(":visible")){this.menu.element.hide();this.menu.blur();this.isNewMenu=true;this._trigger("close",event);}},_change:function(event){if(this.previous!==this._value()){this._trigger("change",event,{item:this.selectedItem});}},_normalize:function(items){if(items.length&&items[0].label&&items[0].value){return items;}
return $.map(items,function(item){if(typeof item==="string"){return{label:item,value:item};}
return $.extend({},item,{label:item.label||item.value,value:item.value||item.label});});},_suggest:function(items){var ul=this.menu.element.empty();this._renderMenu(ul,items);this.isNewMenu=true;this.menu.refresh();ul.show();this._resizeMenu();ul.position($.extend({of:this.element},this.options.position));if(this.options.autoFocus){this.menu.next();}
this._on(this.document,{mousedown:"_closeOnClickOutside"});},_resizeMenu:function(){var ul=this.menu.element;ul.outerWidth(Math.max(ul.width("").outerWidth()+1,this.element.outerWidth()));},_renderMenu:function(ul,items){var that=this;$.each(items,function(index,item){that._renderItemData(ul,item);});},_renderItemData:function(ul,item){return this._renderItem(ul,item).data("ui-autocomplete-item",item);},_renderItem:function(ul,item){return $("<li>").append($("<div>").text(item.label)).appendTo(ul);},_move:function(direction,event){if(!this.menu.element.is(":visible")){this.search(null,event);return;}
if(this.menu.isFirstItem()&&/^previous/.test(direction)||this.menu.isLastItem()&&/^next/.test(direction)){if(!this.isMultiLine){this._value(this.term);}
this.menu.blur();return;}
this.menu[direction](event);},widget:function(){return this.menu.element;},_value:function(){return this.valueMethod.apply(this.element,arguments);},_keyEvent:function(keyEvent,event){if(!this.isMultiLine||this.menu.element.is(":visible")){this._move(keyEvent,event);event.preventDefault();}},_isContentEditable:function(element){if(!element.length){return false;}
var editable=element.prop("contentEditable");if(editable==="inherit"){return this._isContentEditable(element.parent());}
return editable==="true";}});$.extend($.ui.autocomplete,{escapeRegex:function(value){return value.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&");},filter:function(array,term){var matcher=new RegExp($.ui.autocomplete.escapeRegex(term),"i");return $.grep(array,function(value){return matcher.test(value.label||value.value||value);});}});$.widget("ui.autocomplete",$.ui.autocomplete,{options:{messages:{noResults:"No search results.",results:function(amount){return amount+(amount>1?" results are":" result is")+" available, use up and down arrow keys to navigate.";}}},__response:function(content){var message;this._superApply(arguments);if(this.options.disabled||this.cancelSearch){return;}
if(content&&content.length){message=this.options.messages.results(content.length);}else{message=this.options.messages.noResults;}
clearTimeout(this.liveRegionTimer);this.liveRegionTimer=this._delay(function(){this.liveRegion.html($("<div>").text(message));},100);}});var widgetsAutocomplete=$.ui.autocomplete;$.widget("ui.tooltip",{version:"1.13.2",options:{classes:{"ui-tooltip":"ui-corner-all ui-widget-shadow"},content:function(){var title=$(this).attr("title");return $("<a>").text(title).html();},hide:true,items:"[title]:not([disabled])",position:{my:"left top+15",at:"left bottom",collision:"flipfit flip"},show:true,track:false,close:null,open:null},_addDescribedBy:function(elem,id){var describedby=(elem.attr("aria-describedby")||"").split(/\s+/);describedby.push(id);elem.data("ui-tooltip-id",id).attr("aria-describedby",String.prototype.trim.call(describedby.join(" ")));},_removeDescribedBy:function(elem){var id=elem.data("ui-tooltip-id"),describedby=(elem.attr("aria-describedby")||"").split(/\s+/),index=$.inArray(id,describedby);if(index!==-1){describedby.splice(index,1);}
elem.removeData("ui-tooltip-id");describedby=String.prototype.trim.call(describedby.join(" "));if(describedby){elem.attr("aria-describedby",describedby);}else{elem.removeAttr("aria-describedby");}},_create:function(){this._on({mouseover:"open",focusin:"open"});this.tooltips={};this.parents={};this.liveRegion=$("<div>").attr({role:"log","aria-live":"assertive","aria-relevant":"additions"}).appendTo(this.document[0].body);this._addClass(this.liveRegion,null,"ui-helper-hidden-accessible");this.disabledTitles=$([]);},_setOption:function(key,value){var that=this;this._super(key,value);if(key==="content"){$.each(this.tooltips,function(id,tooltipData){that._updateContent(tooltipData.element);});}},_setOptionDisabled:function(value){this[value?"_disable":"_enable"]();},_disable:function(){var that=this;$.each(this.tooltips,function(id,tooltipData){var event=$.Event("blur");event.target=event.currentTarget=tooltipData.element[0];that.close(event,true);});this.disabledTitles=this.disabledTitles.add(this.element.find(this.options.items).addBack().filter(function(){var element=$(this);if(element.is("[title]")){return element.data("ui-tooltip-title",element.attr("title")).removeAttr("title");}}));},_enable:function(){this.disabledTitles.each(function(){var element=$(this);if(element.data("ui-tooltip-title")){element.attr("title",element.data("ui-tooltip-title"));}});this.disabledTitles=$([]);},open:function(event){var that=this,target=$(event?event.target:this.element).closest(this.options.items);if(!target.length||target.data("ui-tooltip-id")){return;}
if(target.attr("title")){target.data("ui-tooltip-title",target.attr("title"));}
target.data("ui-tooltip-open",true);if(event&&event.type==="mouseover"){target.parents().each(function(){var parent=$(this),blurEvent;if(parent.data("ui-tooltip-open")){blurEvent=$.Event("blur");blurEvent.target=blurEvent.currentTarget=this;that.close(blurEvent,true);}
if(parent.attr("title")){parent.uniqueId();that.parents[this.id]={element:this,title:parent.attr("title")};parent.attr("title","");}});}
this._registerCloseHandlers(event,target);this._updateContent(target,event);},_updateContent:function(target,event){var content,contentOption=this.options.content,that=this,eventType=event?event.type:null;if(typeof contentOption==="string"||contentOption.nodeType||contentOption.jquery){return this._open(event,target,contentOption);}
content=contentOption.call(target[0],function(response){that._delay(function(){if(!target.data("ui-tooltip-open")){return;}
if(event){event.type=eventType;}
this._open(event,target,response);});});if(content){this._open(event,target,content);}},_open:function(event,target,content){var tooltipData,tooltip,delayedShow,a11yContent,positionOption=$.extend({},this.options.position);if(!content){return;}
tooltipData=this._find(target);if(tooltipData){tooltipData.tooltip.find(".ui-tooltip-content").html(content);return;}
if(target.is("[title]")){if(event&&event.type==="mouseover"){target.attr("title","");}else{target.removeAttr("title");}}
tooltipData=this._tooltip(target);tooltip=tooltipData.tooltip;this._addDescribedBy(target,tooltip.attr("id"));tooltip.find(".ui-tooltip-content").html(content);this.liveRegion.children().hide();a11yContent=$("<div>").html(tooltip.find(".ui-tooltip-content").html());a11yContent.removeAttr("name").find("[name]").removeAttr("name");a11yContent.removeAttr("id").find("[id]").removeAttr("id");a11yContent.appendTo(this.liveRegion);function position(event){positionOption.of=event;if(tooltip.is(":hidden")){return;}
tooltip.position(positionOption);}
if(this.options.track&&event&&/^mouse/.test(event.type)){this._on(this.document,{mousemove:position});position(event);}else{tooltip.position($.extend({of:target},this.options.position));}
tooltip.hide();this._show(tooltip,this.options.show);if(this.options.track&&this.options.show&&this.options.show.delay){delayedShow=this.delayedShow=setInterval(function(){if(tooltip.is(":visible")){position(positionOption.of);clearInterval(delayedShow);}},13);}
this._trigger("open",event,{tooltip:tooltip});},_registerCloseHandlers:function(event,target){var events={keyup:function(event){if(event.keyCode===$.ui.keyCode.ESCAPE){var fakeEvent=$.Event(event);fakeEvent.currentTarget=target[0];this.close(fakeEvent,true);}}};if(target[0]!==this.element[0]){events.remove=function(){var targetElement=this._find(target);if(targetElement){this._removeTooltip(targetElement.tooltip);}};}
if(!event||event.type==="mouseover"){events.mouseleave="close";}
if(!event||event.type==="focusin"){events.focusout="close";}
this._on(true,target,events);},close:function(event){var tooltip,that=this,target=$(event?event.currentTarget:this.element),tooltipData=this._find(target);if(!tooltipData){target.removeData("ui-tooltip-open");return;}
tooltip=tooltipData.tooltip;if(tooltipData.closing){return;}
clearInterval(this.delayedShow);if(target.data("ui-tooltip-title")&&!target.attr("title")){target.attr("title",target.data("ui-tooltip-title"));}
this._removeDescribedBy(target);tooltipData.hiding=true;tooltip.stop(true);this._hide(tooltip,this.options.hide,function(){that._removeTooltip($(this));});target.removeData("ui-tooltip-open");this._off(target,"mouseleave focusout keyup");if(target[0]!==this.element[0]){this._off(target,"remove");}
this._off(this.document,"mousemove");if(event&&event.type==="mouseleave"){$.each(this.parents,function(id,parent){$(parent.element).attr("title",parent.title);delete that.parents[id];});}
tooltipData.closing=true;this._trigger("close",event,{tooltip:tooltip});if(!tooltipData.hiding){tooltipData.closing=false;}},_tooltip:function(element){var tooltip=$("<div>").attr("role","tooltip"),content=$("<div>").appendTo(tooltip),id=tooltip.uniqueId().attr("id");this._addClass(content,"ui-tooltip-content");this._addClass(tooltip,"ui-tooltip","ui-widget ui-widget-content");tooltip.appendTo(this._appendTo(element));return this.tooltips[id]={element:element,tooltip:tooltip};},_find:function(target){var id=target.data("ui-tooltip-id");return id?this.tooltips[id]:null;},_removeTooltip:function(tooltip){clearInterval(this.delayedShow);tooltip.remove();delete this.tooltips[tooltip.attr("id")];},_appendTo:function(target){var element=target.closest(".ui-front, dialog");if(!element.length){element=this.document[0].body;}
return element;},_destroy:function(){var that=this;$.each(this.tooltips,function(id,tooltipData){var event=$.Event("blur"),element=tooltipData.element;event.target=event.currentTarget=element[0];that.close(event,true);$("#"+id).remove();if(element.data("ui-tooltip-title")){if(!element.attr("title")){element.attr("title",element.data("ui-tooltip-title"));}
element.removeData("ui-tooltip-title");}});this.liveRegion.remove();}});if($.uiBackCompat!==false){$.widget("ui.tooltip",$.ui.tooltip,{options:{tooltipClass:null},_tooltip:function(){var tooltipData=this._superApply(arguments);if(this.options.tooltipClass){tooltipData.tooltip.addClass(this.options.tooltipClass);}
return tooltipData;}});}
var widgetsTooltip=$.ui.tooltip;});
/* jquery/extend */jQuery.extend(jQuery.expr[':'],{imgLink:function(a){return a.href&&a.href.indexOf('.')>-1&&['png','gif','jpg','jpeg','bmp'].includes(getExtension(a.href));},geLink:function(a){return a.href&&a.href.indexOf('.')>-1&&['kml','kmz'].includes(getExtension(a.href));},jwLink:function(a){return a.href&&a.href.indexOf('.')>-1&&['flv','mp4','m4v','mp3','aac'].includes(getExtension(a.href));},mediaLink:function(a){return a.href&&a.href.indexOf('.')>-1&&['mp3','ogg','mp4','m4v','webm','ogv'].includes(getExtension(a.href));},jsLink:function(a){return a.href&&a.protocol=='javascript:';},mailLink:function(a){return a.href&&a.protocol=='mailto:';},ftpLink:function(a){return a.href&&a.protocol=='ftp:';},fakeLink:function(a){return a.href&&getHash(a.href)=='#';},hashLink:function(a){return a.href&&getHash(a.href).length>1;},pageLink:function(a){return a.href&&a.href.indexOf('#')>-1&&a.hostname==location.hostname&&(a.pathname==location.pathname||'/'+a.pathname==location.pathname)&&a.search==location.search;},siteLink:function(a){return a.href&&(a.protocol=='http:'||a.protocol=='https:')&&a.hostname==location.hostname;},inViewport:function(a){const rect=a.getBoundingClientRect();return rect.bottom>=0&&rect.top<=(window.innerHeight||document.documentElement.clientHeight);}});jQuery.fn.extend({hoverfocus:function(fnOver,fnOut){return this.on('mouseenter focusin',fnOver).on('mouseleave focusout',fnOut);},});
/* jquery/cookie */(function(factory){if(typeof define==='function'&&define.amd){define(['jquery'],factory);}else if(typeof exports==='object'){factory(require('jquery'));}else{factory(jQuery);}})(function($){var pluses=/\+/g;function encode(s){return config.raw?s:encodeURIComponent(s);}
function decode(s){return config.raw?s:decodeURIComponent(s);}
function stringifyCookieValue(value){return encode(config.json?JSON.stringify(value):String(value));}
function parseCookieValue(s){if(s.indexOf('"')===0){s=s.slice(1,-1).replace(/\\"/g,'"').replace(/\\\\/g,'\\');}
try{s=decodeURIComponent(s.replace(pluses,' '));return config.json?JSON.parse(s):s;}catch(e){}}
function read(s,converter){var value=config.raw?s:parseCookieValue(s);return $.isFunction(converter)?converter(value):value;}
var config=($.cookie=function(key,value,options){if(value!==undefined&&!$.isFunction(value)){options=$.extend({},config.defaults,options);if(typeof options.expires==='number'){var days=options.expires,t=(options.expires=new Date());t.setTime(+t+days*864e5);}
return(document.cookie=[encode(key),'=',stringifyCookieValue(value),options.expires?'; expires='+options.expires.toUTCString():'',options.path?'; path='+options.path:'',options.domain?'; domain='+options.domain:'',options.secure?'; secure':'',].join(''));}
var result=key?undefined:{};var cookies=document.cookie?document.cookie.split('; '):[];for(var i=0,l=cookies.length;i<l;i++){var parts=cookies[i].split('=');var name=decode(parts.shift());var cookie=parts.join('=');if(key&&key===name){result=read(cookie,value);break;}
if(!key&&(cookie=read(cookie))!==undefined){result[name]=cookie;}}
return result;});config.defaults={};$.removeCookie=function(key,options){if($.cookie(key)===undefined){return false;}
$.cookie(key,'',$.extend({},options,{expires:-1}));return!$.cookie(key);};});
/* jquery/hotkeys */(function(jQuery){jQuery.hotkeys={version:'0.2.0',specialKeys:{8:'backspace',9:'tab',10:'return',13:'return',16:'shift',17:'ctrl',18:'alt',19:'pause',20:'capslock',27:'esc',32:'space',33:'pageup',34:'pagedown',35:'end',36:'home',37:'left',38:'up',39:'right',40:'down',45:'insert',46:'del',59:';',61:'=',96:'0',97:'1',98:'2',99:'3',100:'4',101:'5',102:'6',103:'7',104:'8',105:'9',106:'*',107:'+',109:'-',110:'.',111:'/',112:'f1',113:'f2',114:'f3',115:'f4',116:'f5',117:'f6',118:'f7',119:'f8',120:'f9',121:'f10',122:'f11',123:'f12',144:'numlock',145:'scroll',173:'-',186:';',187:'=',188:',',189:'-',190:'.',191:'/',192:'`',219:'[',220:'\\',221:']',222:"'",},shiftNums:{'`':'~',1:'!',2:'@',3:'#',4:'$',5:'%',6:'^',7:'&',8:'*',9:'(',0:')','-':'_','=':'+',';':': ',"'":'"',',':'<','.':'>','/':'?','\\':'|',},textAcceptingInputTypes:['text','password','number','email','url','range','date','month','week','time','datetime','datetime-local','search','color','tel'],textInputTypes:/textarea|input|select/i,options:{filterInputAcceptingElements:true,filterTextInputs:true,filterContentEditable:true,},};function keyHandler(handleObj){if(typeof handleObj.data==='string'){handleObj.data={keys:handleObj.data,};}
if(!handleObj.data||!handleObj.data.keys||typeof handleObj.data.keys!=='string'){return;}
var origHandler=handleObj.handler,keys=handleObj.data.keys.toLowerCase().split(' ');handleObj.handler=function(event){if(this!==event.target&&((jQuery.hotkeys.options.filterInputAcceptingElements&&jQuery.hotkeys.textInputTypes.test(event.target.nodeName))||(jQuery.hotkeys.options.filterContentEditable&&jQuery(event.target).attr('contenteditable'))||(jQuery.hotkeys.options.filterTextInputs&&jQuery.inArray(event.target.type,jQuery.hotkeys.textAcceptingInputTypes)>-1))){return;}
var special=event.type!=='keypress'&&jQuery.hotkeys.specialKeys[event.which],character=String.fromCharCode(event.which).toLowerCase(),modif='',possible={};jQuery.each(['alt','ctrl','shift'],function(index,specialKey){if(event[specialKey+'Key']&&special!==specialKey){modif+=specialKey+'+';}});if(event.metaKey&&!event.ctrlKey&&special!=='meta'){modif+='meta+';}
if(event.metaKey&&special!=='meta'&&modif.indexOf('alt+ctrl+shift+')>-1){modif=modif.replace('alt+ctrl+shift+','hyper+');}
if(special){possible[modif+special]=true;}else{possible[modif+character]=true;possible[modif+jQuery.hotkeys.shiftNums[character]]=true;if(modif==='shift+'){possible[jQuery.hotkeys.shiftNums[character]]=true;}}
for(var i=0,l=keys.length;i<l;i++){if(possible[keys[i]]){return origHandler.apply(this,arguments);}}};}
jQuery.each(['keydown','keyup','keypress'],function(){jQuery.event.special[this]={add:keyHandler,};});})(jQuery||this.jQuery||window.jQuery);
/* jquery/showHref */(function($){$.fn.showHref=function(options){var startNum,opts=$.extend({},$.fn.showHref.defaults,options);if(opts.baseNum>=0){startNum=opts.baseNum;$(opts.hrefsBox).empty();$(this).find('span.'+opts.refClass).remove();}else{startNum=$(opts.hrefWrapper,opts.hrefsBox).length;}
return this.each(function(){if($(this).is(':jsLink')){this.show=opts.jsLinks?this.href:null;}else if($(this).is(':mailLink')){this.show=opts.mailLinks?(opts.stripMailto?this.href.substring(7):this.href):null;}
else if($(this).is(':ftpLink')){this.show=opts.ftpLinks?this.href:null;}else if($(this).is(':pageLink')){this.show=opts.pageLinks?this.href:null;}else if($(this).is(':siteLink')){this.show=opts.siteLinks?this.href:null;}else{this.show=this.href;}
if(this.show!=null){startNum++;$(this).append('<span class="'+opts.refClass+'">&nbsp;['+startNum+']</span>');$(opts.hrefsBox).append('<'+opts.hrefWrapper+'><span>['+startNum+']</span> '+this.show+'</'+opts.hrefWrapper+'>');}});};$.fn.showHref.defaults={baseNum:-1,refClass:'hrefNumber',hrefsBox:'#Hrefs',hrefWrapper:'p',mailLinks:true,ftpLinks:true,jsLinks:false,pageLinks:false,siteLinks:false,stripMailto:true,};})(jQuery);
/* jquery/alphanum */(function($){$.fn.alphanum=function(settings){var combinedSettings=getCombinedSettingsAlphaNum(settings);var $collection=this;setupEventHandlers($collection,trimAlphaNum,combinedSettings);return this;};$.fn.alpha=function(settings){var defaultAlphaSettings=getCombinedSettingsAlphaNum('alpha');var combinedSettings=getCombinedSettingsAlphaNum(settings,defaultAlphaSettings);var $collection=this;setupEventHandlers($collection,trimAlphaNum,combinedSettings);return this;};$.fn.numeric=function(settings){var combinedSettings=getCombinedSettingsNum(settings);var $collection=this;setupEventHandlers($collection,trimNum,combinedSettings);$collection.on('blur',function(){numericField_Blur(this,combinedSettings);});return this;};var DEFAULT_SETTINGS_ALPHANUM={allow:'',disallow:'',allowSpace:true,allowNewline:true,allowNumeric:true,allowUpper:true,allowLower:true,allowCaseless:true,allowLatin:true,allowOtherCharSets:true,forceUpper:false,forceLower:false,maxLength:NaN};var DEFAULT_SETTINGS_NUM={allowPlus:false,allowMinus:true,allowThouSep:true,allowDecSep:true,allowLeadingSpaces:false,maxDigits:NaN,maxDecimalPlaces:NaN,maxPreDecimalPlaces:NaN,max:NaN,min:NaN};var CONVENIENCE_SETTINGS_ALPHANUM={alpha:{allowNumeric:false},upper:{allowNumeric:false,allowUpper:true,allowLower:false,allowCaseless:true},lower:{allowNumeric:false,allowUpper:false,allowLower:true,allowCaseless:true}};var CONVENIENCE_SETTINGS_NUMERIC={integer:{allowPlus:false,allowMinus:true,allowThouSep:false,allowDecSep:false},positiveInteger:{allowPlus:false,allowMinus:false,allowThouSep:false,allowDecSep:false}};var BLACKLIST=getBlacklistAscii()+getBlacklistNonAscii();var THOU_SEP=',';var DEC_SEP='.';var DIGITS=getDigitsMap();var LATIN_CHARS=getLatinCharsSet();function getBlacklistAscii(){var blacklist='!@#$%^&*()+=[]\\\';,/{}|":<>?~`.-_';blacklist+=' ';return blacklist;}
function getBlacklistNonAscii(){var blacklist='\xAC'+'\u20AC'+'\xA3'+'\xA6';return blacklist;}
function setupEventHandlers($textboxes,trimFunction,settings){$textboxes.each(function(){var $textbox=$(this);$textbox.off('.alphanum').on('keyup.alphanum change.alphanum paste.alphanum',function(e){var pastedText='';if(e.originalEvent&&e.originalEvent.clipboardData&&e.originalEvent.clipboardData.getData)
pastedText=e.originalEvent.clipboardData.getData('text/plain');setTimeout(function(){trimTextbox($textbox,trimFunction,settings,pastedText);},0);}).on('keypress.alphanum',function(e){var charCode=!e.charCode?e.which:e.charCode;if(isControlKey(charCode)||e.ctrlKey||e.metaKey)
return;var newChar=String.fromCharCode(charCode);var selectionObject=$textbox.selection();var start=selectionObject.start;var end=selectionObject.end;var textBeforeKeypress=$textbox.val();var potentialTextAfterKeypress=textBeforeKeypress.substring(0,start)+newChar+textBeforeKeypress.substring(end);var validatedText=trimFunction(potentialTextAfterKeypress,settings);if(validatedText!=potentialTextAfterKeypress)e.preventDefault();});});}
function numericField_Blur(inputBox,settings){var fieldValueNumeric=parseFloat($(inputBox).val());var $inputBox=$(inputBox);if(isNaN(fieldValueNumeric)){$inputBox.val('');return;}
if(isNumeric(settings.min)&&fieldValueNumeric<settings.min)$inputBox.val('');if(isNumeric(settings.max)&&fieldValueNumeric>settings.max)$inputBox.val('');}
function isNumeric(value){return!isNaN(value);}
function isControlKey(charCode){if(charCode>=32)return false;if(charCode==10)return false;if(charCode==13)return false;return true;}
function trimTextbox($textBox,trimFunction,settings,pastedText){var inputString=$textBox.val();if(inputString==''&&pastedText.length>0)inputString=pastedText;var outputString=trimFunction(inputString,settings);if(inputString==outputString)return;var caretPos=$textBox.alphanum_caret();$textBox.val(outputString);if(inputString.length==outputString.length+1)$textBox.alphanum_caret(caretPos-1);else $textBox.alphanum_caret(caretPos);}
function getCombinedSettingsAlphaNum(settings,defaultSettings){if(typeof defaultSettings=='undefined')defaultSettings=DEFAULT_SETTINGS_ALPHANUM;var userSettings,combinedSettings={};if(typeof settings==='string')userSettings=CONVENIENCE_SETTINGS_ALPHANUM[settings];else if(typeof settings=='undefined')userSettings={};else userSettings=settings;$.extend(combinedSettings,defaultSettings,userSettings);if(typeof combinedSettings.blacklist=='undefined')
combinedSettings.blacklistSet=getBlacklistSet(combinedSettings.allow,combinedSettings.disallow);return combinedSettings;}
function getCombinedSettingsNum(settings){var userSettings,combinedSettings={};if(typeof settings==='string')userSettings=CONVENIENCE_SETTINGS_NUMERIC[settings];else if(typeof settings=='undefined')userSettings={};else userSettings=settings;$.extend(combinedSettings,DEFAULT_SETTINGS_NUM,userSettings);return combinedSettings;}
function alphanum_allowChar(validatedStringFragment,Char,settings){if(settings.maxLength&&validatedStringFragment.length>=settings.maxLength)return false;if(settings.allow.indexOf(Char)>=0)return true;if(settings.allowSpace&&Char==' ')return true;if(!settings.allowNewline&&(Char=='\n'||Char=='\r'))return false;if(settings.blacklistSet.contains(Char))return false;if(!settings.allowNumeric&&DIGITS[Char])return false;if(!settings.allowUpper&&isUpper(Char))return false;if(!settings.allowLower&&isLower(Char))return false;if(!settings.allowCaseless&&isCaseless(Char))return false;if(!settings.allowLatin&&LATIN_CHARS.contains(Char))return false;if(!settings.allowOtherCharSets){if(DIGITS[Char]||LATIN_CHARS.contains(Char))return true;else return false;}
return true;}
function numeric_allowChar(validatedStringFragment,Char,settings){if(DIGITS[Char]){if(isMaxDigitsReached(validatedStringFragment,settings))return false;if(isMaxPreDecimalsReached(validatedStringFragment,settings))return false;if(isMaxDecimalsReached(validatedStringFragment,settings))return false;if(isGreaterThanMax(validatedStringFragment+Char,settings))return false;if(isLessThanMin(validatedStringFragment+Char,settings))return false;return true;}
if(settings.allowPlus&&Char=='+'&&validatedStringFragment=='')return true;if(settings.allowMinus&&Char=='-'&&validatedStringFragment=='')return true;if(Char==THOU_SEP&&settings.allowThouSep&&allowThouSep(validatedStringFragment))return true;if(Char==DEC_SEP){if(validatedStringFragment.indexOf(DEC_SEP)>=0)return false;if(settings.allowDecSep&&settings.maxDecimalPlaces===0)return false;if(settings.allowDecSep)return true;}
return false;}
function countDigits(string){string=string+'';return string.replace(/[^0-9]/g,'').length;}
function isMaxDigitsReached(string,settings){var maxDigits=settings.maxDigits;if(maxDigits===''||isNaN(maxDigits))return false;var numDigits=countDigits(string);if(numDigits>=maxDigits)return true;return false;}
function isMaxDecimalsReached(string,settings){var maxDecimalPlaces=settings.maxDecimalPlaces;if(maxDecimalPlaces===''||isNaN(maxDecimalPlaces))return false;var indexOfDecimalPoint=string.indexOf(DEC_SEP);if(indexOfDecimalPoint==-1)return false;var decimalSubstring=string.substring(indexOfDecimalPoint);var numDecimals=countDigits(decimalSubstring);if(numDecimals>=maxDecimalPlaces)return true;return false;}
function isMaxPreDecimalsReached(string,settings){var maxPreDecimalPlaces=settings.maxPreDecimalPlaces;if(maxPreDecimalPlaces===''||isNaN(maxPreDecimalPlaces))return false;var indexOfDecimalPoint=string.indexOf(DEC_SEP);if(indexOfDecimalPoint>=0)return false;var numPreDecimalDigits=countDigits(string);if(numPreDecimalDigits>=maxPreDecimalPlaces)return true;return false;}
function isGreaterThanMax(numericString,settings){if(!settings.max||settings.max<0)return false;var outputNumber=parseFloat(numericString);if(outputNumber>settings.max)return true;return false;}
function isLessThanMin(numericString,settings){if(!settings.min||settings.min>0)return false;var outputNumber=parseFloat(numericString);if(outputNumber<settings.min)return true;return false;}
function trimAlphaNum(inputString,settings){if(typeof inputString!='string')return inputString;var inChars=inputString.split('');var outChars=[];var i=0;var Char;for(i=0;i<inChars.length;i++){Char=inChars[i];var validatedStringFragment=outChars.join('');if(alphanum_allowChar(validatedStringFragment,Char,settings))outChars.push(Char);}
var outputString=outChars.join('');if(settings.forceLower)outputString=outputString.toLowerCase();else if(settings.forceUpper)outputString=outputString.toUpperCase();return outputString;}
function trimNum(inputString,settings){if(typeof inputString!='string')return inputString;var inChars=inputString.split('');var outChars=[];var i=0;var Char;for(i=0;i<inChars.length;i++){Char=inChars[i];var validatedStringFragment=outChars.join('');if(numeric_allowChar(validatedStringFragment,Char,settings))outChars.push(Char);}
return outChars.join('');}
function isUpper(Char){var upper=Char.toUpperCase();var lower=Char.toLowerCase();if(Char==upper&&upper!=lower)return true;else return false;}
function isLower(Char){var upper=Char.toUpperCase();var lower=Char.toLowerCase();if(Char==lower&&upper!=lower)return true;else return false;}
function isCaseless(Char){if(Char.toUpperCase()==Char.toLowerCase())return true;else return false;}
function getBlacklistSet(allow,disallow){var setOfBadChars=new Set(BLACKLIST+disallow);var setOfGoodChars=new Set(allow);var blacklistSet=setOfBadChars.subtract(setOfGoodChars);return blacklistSet;}
function getDigitsMap(){var array='0123456789'.split('');var map={};var i=0;var digit;for(i=0;i<array.length;i++){digit=array[i];map[digit]=true;}
return map;}
function getLatinCharsSet(){var lower='abcdefghijklmnopqrstuvwxyz';var upper=lower.toUpperCase();var azAZ=new Set(lower+upper);return azAZ;}
function allowThouSep(currentString){if(currentString.length==0)return false;var posOfDecSep=currentString.indexOf(DEC_SEP);if(posOfDecSep>=0)return false;var posOfFirstThouSep=currentString.indexOf(THOU_SEP);if(posOfFirstThouSep<0)return true;var posOfLastThouSep=currentString.lastIndexOf(THOU_SEP);var charsSinceLastThouSep=currentString.length-posOfLastThouSep-1;if(charsSinceLastThouSep<3)return false;var digitsSinceFirstThouSep=countDigits(currentString.substring(posOfFirstThouSep));if(digitsSinceFirstThouSep%3>0)return false;return true;}
function Set(elems){if(typeof elems=='string')this.map=stringToMap(elems);else this.map={};}
Set.prototype.add=function(set){var newSet=this.clone();for(var key in set.map)newSet.map[key]=true;return newSet;};Set.prototype.subtract=function(set){var newSet=this.clone();for(var key in set.map)delete newSet.map[key];return newSet;};Set.prototype.contains=function(key){if(this.map[key])return true;else return false;};Set.prototype.clone=function(){var newSet=new Set();for(var key in this.map)newSet.map[key]=true;return newSet;};function stringToMap(string){var map={};var array=string.split('');var i=0;var Char;for(i=0;i<array.length;i++){Char=array[i];map[Char]=true;}
return map;}
$.fn.alphanum.backdoorAlphaNum=function(inputString,settings){var combinedSettings=getCombinedSettingsAlphaNum(settings);return trimAlphaNum(inputString,combinedSettings);};$.fn.alphanum.backdoorNumeric=function(inputString,settings){var combinedSettings=getCombinedSettingsNum(settings);return trimNum(inputString,combinedSettings);};$.fn.alphanum.setNumericSeparators=function(settings){if(settings.thousandsSeparator.length!=1)return;if(settings.decimalSeparator.length!=1)return;THOU_SEP=settings.thousandsSeparator;DEC_SEP=settings.decimalSeparator;};})(jQuery);(function($){function caretTo(el,index){if(el.createTextRange){var range=el.createTextRange();range.move('character',index);range.select();}else if(el.selectionStart!=null){el.focus();el.setSelectionRange(index,index);}}
function caretPos(el){if('selection'in document){var range=el.createTextRange();try{range.setEndPoint('EndToStart',document.selection.createRange());}catch(e){return 0;}
return range.text.length;}else if(el.selectionStart!=null){return el.selectionStart;}}
$.fn.alphanum_caret=function(index,offset){if(typeof index==='undefined'){return caretPos(this.get(0));}
return this.queue(function(next){if(isNaN(index)){var i=$(this).val().indexOf(index);if(offset===true){i+=index.length;}else if(typeof offset!=='undefined'){i+=offset;}
caretTo(this,i);}else{caretTo(this,index);}
next();});};})(jQuery);(function(e){var t=function(e){return e.replace(/([a-z])([a-z]+)/gi,function(e,t,n){return t+n.toLowerCase();}).replace(/_/g,'');},n=function(e){return e.replace(/^([a-z]+)_TO_([a-z]+)/i,function(e,t,n){return n+'_TO_'+t;});},r=function(e){return e?e.ownerDocument.defaultView||e.ownerDocument.parentWindow:window;},i=function(t,n){var r=e.Range.current(t).clone(),i=e.Range(t).select(t);if(!r.overlaps(i)){return null;}
if(r.compare('START_TO_START',i)<1){startPos=0;r.move('START_TO_START',i);}else{fromElementToCurrent=i.clone();fromElementToCurrent.move('END_TO_START',r);startPos=fromElementToCurrent.toString().length;}
if(r.compare('END_TO_END',i)>=0){endPos=i.toString().length;}else{endPos=startPos+r.toString().length;}
return{start:startPos,end:endPos};},s=function(t){var n=r(t);if(t.selectionStart!==undefined){if(document.activeElement&&document.activeElement!=t&&t.selectionStart==t.selectionEnd&&t.selectionStart==0){return{start:t.value.length,end:t.value.length};}
return{start:t.selectionStart,end:t.selectionEnd};}else if(n.getSelection){return i(t,n);}else{try{if(t.nodeName.toLowerCase()=='input'){var s=r(t).document.selection.createRange(),o=t.createTextRange();o.setEndPoint('EndToStart',s);var u=o.text.length;return{start:u,end:u+s.text.length};}else{var a=i(t,n);if(!a){return a;}
var f=e.Range.current().clone(),l=f.clone().collapse().range,c=f.clone().collapse(false).range;l.moveStart('character',-1);c.moveStart('character',-1);if(a.startPos!=0&&l.text==''){a.startPos+=2;}
if(a.endPos!=0&&c.text==''){a.endPos+=2;}
return a;}}catch(h){return{start:t.value.length,end:t.value.length};}}},o=function(e,t,n){var i=r(e);if(e.setSelectionRange){if(n===undefined){e.focus();e.setSelectionRange(t,t);}else{e.select();e.selectionStart=t;e.selectionEnd=n;}}else if(e.createTextRange){var s=e.createTextRange();s.moveStart('character',t);n=n||t;s.moveEnd('character',n-e.value.length);s.select();}else if(i.getSelection){var o=i.document,u=i.getSelection(),f=o.createRange(),l=[t,n!==undefined?n:t];a([e],l);f.setStart(l[0].el,l[0].count);f.setEnd(l[1].el,l[1].count);u.removeAllRanges();u.addRange(f);}else if(i.document.body.createTextRange){var f=document.body.createTextRange();f.moveToElementText(e);f.collapse();f.moveStart('character',t);f.moveEnd('character',n!==undefined?n:t);f.select();}},u=function(e,t,n,r){if(typeof n[0]==='number'&&n[0]<t){n[0]={el:r,count:n[0]-e};}
if(typeof n[1]==='number'&&n[1]<=t){n[1]={el:r,count:n[1]-e};}},a=function(e,t,n){var r,i;n=n||0;for(var s=0;e[s];s++){r=e[s];if(r.nodeType===3||r.nodeType===4){i=n;n+=r.nodeValue.length;u(i,n,t,r);}else if(r.nodeType!==8){n=a(r.childNodes,t,n);}}
return n;};jQuery.fn.selection=function(e,t){if(e!==undefined){return this.each(function(){o(this,e,t);});}else{return s(this[0]);}};e.fn.selection.getCharElement=a;})(jQuery);
/* validar */var validando=0;function getLabel(id){var re=/^(\*\s)?([^.:*]+)(:|\.)?(\s\*)?$/i;var bits=re.exec($('label[for="'+id+'"]').text());if(bits){return bits[2];}}
function getLegend(campo){return $(campo).parents('fieldset').find('legend').text();}
var datePatterns=[{re:/^((hoy)|(today))$/i,handler:function(){return new Date();}},{re:/^((mañana)|(tomorrow))$/i,handler:function(){var d=new Date();d.setDate(d.getDate()+1);return d;}},{re:/^(\d{1,2})$/i,handler:function(bits){var d=new Date();d.setDate(parseInt(bits[1],10));return d;}},{re:/^(\d{1,2})-(\d{1,2})$/i,handler:function(bits){var d=new Date();d.setMonth(parseInt(bits[2],10)-1);d.setDate(parseInt(bits[1],10));return d;}},{re:/(\d{1,2})-(\d{1,2})-(\d{4})/,handler:function(bits){var d=new Date();d.setYear(parseInt(bits[3]));d.setMonth(parseInt(bits[2],10)-1);d.setDate(parseInt(bits[1],10));return d;}}];function parseDateString(cadena){for(var i=0;i<datePatterns.length;i++){var re=datePatterns[i].re;var handler=datePatterns[i].handler;var bits=re.exec(cadena);if(bits){return handler(bits);}}
return false;}
function parseDateFixed(cadena,pattern){var dateFixedPatterns=[{pat:'dd-mm-yyyy',re:/(\d{1,2})-(\d{1,2})-(\d{4})/,handler:function(bits){var d=new Date();d.setYear(parseInt(bits[3]));d.setMonth(parseInt(bits[2],10)-1);d.setDate(parseInt(bits[1],10));return d;}},{pat:'mm-dd-yyyy',re:/(\d{1,2})-(\d{1,2})-(\d{4})/,handler:function(bits){var d=new Date();d.setYear(parseInt(bits[3]));d.setMonth(parseInt(bits[1],10)-1);d.setDate(parseInt(bits[2],10));return d;}},{pat:'yyyy-mm-dd',re:/(\d{4})-(\d{1,2})-(\d{1,2})/,handler:function(bits){var d=new Date();d.setYear(parseInt(bits[1]));d.setMonth(parseInt(bits[2],10)-1);d.setDate(parseInt(bits[3],10));return d;}}];var i;for(var p=0;p<dateFixedPatterns.length;p++){if(dateFixedPatterns[p].pat==pattern){i=p;break;}}
var re=dateFixedPatterns[i].re;var handler=dateFixedPatterns[i].handler;var bits=re.exec(cadena);if(bits){return handler(bits);}
return false;}
function validaForm(theForm,theFieldsets,theMsgBox,lang=$('html').attr('lang')){if(validando){return false;}
let errBadSub,errMustFill,errMustSel,errBadMail1,errBadMail2,errBadNum1,errBadNum2,errBadDate1a,errBadDate1b,errBadDate1c,errBadDate2a,errBadDate2b,errBadDate2c,errMinCar1,errMinCar2,errMinCar3,errRecaptcha;if(lang=='en'){errBadSub='Bad form submission:';errMustFill='It is necessary to fill in the field \'';errMustSel='It is necessary to choose an option in the field \'';errBadMail1='The e-mail address entered in the field \'';errBadMail2='\' is not valid.';errBadNum1='The text to enter in the field \'';errBadNum2='\' must be numeric (or leave it blank instead).';errBadDate1a='The date entered is not in the right format.';errBadDate1b='The date entered in the field \'';errBadDate1c='\' is not in the right format.';errBadDate2a='The date entered should be in the following format: ';errBadDate2b='The date entered in the field \'';errBadDate2c='\' should be in the following format: ';errMinCar1='The text you write in the field \'';errMinCar2='\' must have at least ';errMinCar3=' characters.';errRecaptcha='It is necessary to fill in the reCAPTCHA test.';}else if(lang=='es'){errBadSub='El formulario no ha sido bien rellenado:';errMustFill='Es necesario rellenar el campo \'';errMustSel='Es necesario seleccionar una opción en el campo \'';errBadMail1='La dirección de correo electrónico introducida en el campo \'';errBadMail2='\' no es válida.';errBadNum1='El contenido del campo \'';errBadNum2='\' ha de ser numérico (puedes dejarlo en blanco).';errBadDate1a='La fecha introducida no está en el formato correcto.';errBadDate1b='La fecha introducida en el campo \'';errBadDate1c='\' no está en el formato correcto.';errBadDate2a='La fecha introducida debería estar en el siguiente formato: ';errBadDate2b='La fecha introducida en el campo \'';errBadDate2c='\' debería estar en el siguiente formato: ';errMinCar1='El texto que escribas en el campo \'';errMinCar2='\' debe tener al menos ';errMinCar3=' caracteres.';errRecaptcha='Es necesario realizar el test reCAPTCHA.';}
validando=1;var thisForm=document.forms[theForm.name]||document.forms[theForm]||$(theForm)[0];var $context=theFieldsets?$(thisForm).find(theFieldsets):$(thisForm);var errFocus=false;var marca=false;var errMsg='';var salto=theMsgBox?'<br>&#183; ':'\n &#183; ';var labels=$context.find('label:visible');var elts=$context.find(':input:visible');var eltsNum=elts.length;var disab=new Array();for(var i=0;i<eltsNum;i++){var elt=elts[i];var tipo=elt.type.toLowerCase();if(!elt.disabled&&tipo!='hidden'&&!$(elt).parents(':hidden').not('body, html').length){if(tipo=='submit'||elt.tagName.toLowerCase()=='button'){elt.disabled=true;disab[disab.length]=elt;continue;}
if((tipo=='checkbox'||tipo=='radio')&&$('input[name="'+elt.name+'"]:enabled').index(elt)>0){continue;}
var nombre=elt.name;var valor=elt.value;var largoTotal=valor.length;var largo=valor.replace(/\s/gi,'').length;var texto=getLabel(elt.id);var legend=getLegend(elt);if(elt.getAttribute('required')!=null&&(tipo=='text'||tipo=='password'||tipo=='email'||tipo=='number'||tipo=='search'||tipo=='textarea')&&largo==0){if(texto){errMsg=errMsg+salto+errMustFill+texto+'\'.';}else if(legend&&errMsg.indexOf(legend)<0){errMsg=errMsg+salto+errMustFillVar1+legend+errMustFillVar2;}
if(!errFocus){errFocus=elt;}}
if(elt.getAttribute('required')!=null&&(tipo=='select-one'||tipo=='select-multiple')&&(largo==0||valor=='placeholder')){errMsg=errMsg+salto+errMustSel+texto+'\'.';if(!errFocus){errFocus=elt;}}
if(tipo=='email'&&(largo>0&&!regexMail.test(valor))){errMsg=errMsg+salto+errBadMail1+texto+errBadMail2;if(!errFocus){errFocus=elt;}}
if(elt.getAttribute('isnum')&&(tipo=='text'||tipo=='number')&&(largo>0&&!regexNum.test(valor))){errMsg=errMsg+salto+errBadNum1+texto+errBadNum2;if(!errFocus){errFocus=elt;}}
if(elt.getAttribute('dateformat')&&tipo=='text'&&largo>0){var df=elt.getAttribute('dateformat');if(!parseDateFixed(valor,df)){if(!texto){errMsg=errMsg+salto+errBadDate2a+df;}else{errMsg=errMsg+salto+errBadDate2b+texto+errBadDate2c+df;}
if(!errFocus){errFocus=elt;}}}
if(elt.getAttribute('fecha')&&tipo=='text'&&largo>0){if(parseDateString(valor)){var d=parseDateString(valor);elt.value=d.getDate()+'-'+(d.getMonth()+1)+'-'+d.getFullYear();}else{if(!texto){errMsg=errMsg+salto+errBadDate1a;}else{errMsg=errMsg+salto+errBadDate1b+texto+errBadDate1c;}
if(!errFocus){errFocus=elt;}}}
if(elt.getAttribute('longmin')&&(tipo=='text'||tipo=='textarea')){var longmin=elt.getAttribute('longmin');if(largoTotal<longmin){if(largoTotal==0){errMsg=errMsg+salto+errMustFill+texto+'\'.';}else{errMsg=errMsg+
salto+
errMinCar1+
texto+
errMinCar2+
longmin+
errMinCar3;}
if(!errFocus){errFocus=elt;}}}
if(elt.getAttribute('depbin')&&(tipo=='text'||tipo=='textarea')&&largo>0){var depbin=elt.getAttribute('depbin');if(thisForm.elements[depbin].value.length==0){errMsg=errMsg+salto+errMustFill+getLabel(thisForm.elements[depbin].id)+'\'.';if(!errFocus){errFocus=thisForm.elements[depbin];}}}
if(elt.dataset.depsuma&&(tipo=='text'||tipo=='textarea')){var depsuma=elt.dataset.depsuma;var sumadep=elt.dataset.sumadep;var sumadepnow=0;var campodep=depsuma.split(' ');for(var j=0;j<campodep.length;j++){if(thisForm.elements[campodep[j]].value!=null){sumadepnow=sumadepnow+thisForm.elements[campodep[j]].value.length;}}
if(sumadepnow<sumadep){errMsg=errMsg+salto+elt.dataset.errorDepsuma;if(!errFocus){errFocus=elt;}}}
if(elt.getAttribute('required')!=null&&(tipo=='checkbox'||tipo=='radio')){marca=false;for(j=0;j<thisForm.elements[nombre].length;j++){if(thisForm.elements[nombre][j].checked){marca=true;break;}}
if(!marca){if(elt.dataset.errorRequired){errMsg=errMsg+salto+elt.dataset.errorRequired;}else{errMsg=errMsg+salto+errMustSel+texto+'\'.';}
if(!errFocus){errFocus=elt;}}}
if(elt.dataset.gruporeq&&(tipo=='checkbox'||tipo=='radio')){var gruporeq=elt.dataset.gruporeq;var camporeq=gruporeq.split(' ');marca=false;for(j=0;j<camporeq.length;j++){for(var k=0;k<thisForm.elements[camporeq[j]].length;k++){if(thisForm.elements[camporeq[j]][k].checked){marca=true;break;}}
if(marca==true){break;}}
if(!marca){errMsg=errMsg+salto+elt.dataset.errorGruporeq;if(!errFocus){errFocus=elt;}}}}}
if($context.find('.g-recaptcha').length&&!grecaptcha.getResponse()){errMsg=errMsg+salto+errRecaptcha;}
if(errMsg!=''){errMsg=errBadSub+errMsg;if(theMsgBox){$(theMsgBox).html(errMsg);}else{alert(errMsg);}
if(errFocus){errFocus.focus();}
for(i=0;i<disab.length;i++){disab[i].disabled=false;}
--validando;return false;}
for(i=0;i<disab.length;i++){disab[i].disabled=false;}
--validando;return true;}
function posInputMsg(){if($(document.activeElement).is(':input[minlength], :input[maxlength]')){const $theInput=$(document.activeElement),w=$theInput.outerWidth(),o=$theInput.offset(),l=o.left,t=o.top+$theInput.outerHeight();$('#inputmsg').width(w).offset({left:l,top:t});}}
function writeInputMsg(elt,lang=$('html').attr('lang')){let msgCharsOfMin,msgCharsOfMax,msgAndMax;if(lang=='en'){msgCharsOfMin=' characters written. Minimum: ';msgCharsOfMax=' characters left';msgAndMax='. Maximum: ';}else if(lang=='es'){msgCharsOfMin=' caracteres escritos de un mínimo de ';msgCharsOfMax=' caracteres restantes';msgAndMax=' y un máximo de ';}
let theStr='';const minlength=parseInt(elt.getAttribute('minlength'));const maxlength=parseInt(elt.getAttribute('maxlength'));const arrRetWin=escape(elt.value).match(/%0D%0A/gi);let cntRetWin=arrRetWin?arrRetWin.length:0;let charnow=elt.value.length-cntRetWin;if(maxlength&&charnow>maxlength){if(escape(elt.value.substring(elt.value.length-2,elt.value.length))=='%0D%0A'){elt.value=elt.value.substring(0,elt.value.length-2);cntRetWin--;}
elt.value=elt.value.substring(0,maxlength+cntRetWin);charnow=elt.value.length-cntRetWin;}
if(minlength&&maxlength){theStr=charnow+msgCharsOfMin+minlength+msgAndMax+maxlength+'.';}else if(maxlength){theStr=parseInt(maxlength-charnow)+msgCharsOfMax+'.';}else if(minlength){if(charnow<=minlength){theStr=charnow+msgCharsOfMin+minlength+'.';}else{theStr='';}}
$(':animated').promise().done(function(){posInputMsg();$('#inputmsg').text(theStr);});}
$(document).ready(function(){$('body').prepend('<span id="inputmsg"></span>');$(document).on('input',':input[minlength], :input[maxlength]',function(){writeInputMsg(this);}).on('blur',':input[minlength], :input[maxlength]',function(){$('#inputmsg').empty();});});
/* comun */const is_safari=/constructor/i.test(window.HTMLElement)||(function(p){return p.toString()==='[object SafariRemoteNotification]';})(!window['safari']||(typeof safari!=='undefined'&&window['safari'].pushNotification));const is_firefox=typeof InstallTrigger!=='undefined';const is_blink=!!window.chrome;const is_ie=/*@cc_on!@*/ false||!!document.documentMode;const is_mobile='ontouchstart'in window||(window.DocumentTouch&&document instanceof DocumentTouch);const regexMail=/^(("[^"\f\n\r\t\v\b]+")|([\w!#$%&'*+\-~/^`|{}]+(\.[\w!#$%&'*+\-~/^`|{}]+)*))@((\[(((25[0-5])|(2[0-4][0-9])|([0-1]?[0-9]?[0-9]))\.((25[0-5])|(2[0-4][0-9])|([0-1]?[0-9]?[0-9]))\.((25[0-5])|(2[0-4][0-9])|([0-1]?[0-9]?[0-9]))\.((25[0-5])|(2[0-4][0-9])|([0-1]?[0-9]?[0-9])))\])|(((25[0-5])|(2[0-4][0-9])|([0-1]?[0-9]?[0-9]))\.((25[0-5])|(2[0-4][0-9])|([0-1]?[0-9]?[0-9]))\.((25[0-5])|(2[0-4][0-9])|([0-1]?[0-9]?[0-9]))\.((25[0-5])|(2[0-4][0-9])|([0-1]?[0-9]?[0-9])))|((([A-Za-z0-9-])+\.)+[A-Za-z-]+))$/;const regexNum=/(^-?\d\d*\.\d*$)|(^-?\d\d*$)|(^-?\.\d\d*$)/;$(document).ready(function(){$('.gotop').on('click',function(){window.scroll({top:0,left:0,behavior:'smooth'});return false;});$('a[sendform]').on('click',function(){document.forms[this.getAttribute('sendform')].submit();return false;});$('a[goback]').on('click',function(){history.go(-1);return false;});$('a[close]').on('click',function(){window.close();return false;});$('a[men1]').on('click',function(){window.location.href='mailto:'+this.getAttribute('men1')+'@'+this.getAttribute('men2')+'.'+this.getAttribute('men3');return false;});$('img.nomenu').each(function(){this.oncontextmenu=function(){return false;};this.onselectstart=function(){return false;};this.ondragstart=function(){return false;};});});function preloadImages(...theArgs){const d=document;if(!d.preload){d.preload=[];}
let j=d.preload.length;for(const arg of theArgs){if(arg.charAt(0)!='#'){d.preload[j]=new Image();d.preload[j++].src=arg;}}}
function preloadImagesJQ(...theArgs){for(const arg of theArgs){$('<img />',{src:arg});}}
function statusBlank(){window.status='';return true;}
function inViewport(elt,atleast=0){const rect=elt.getBoundingClientRect();return rect.bottom>=atleast&&rect.top+atleast<=(window.innerHeight||document.documentElement.clientHeight);}
function isBelowTop(elt){return elt.getBoundingClientRect().top>=0;}
function isAboveBottom(elt,offset=0){return elt.getBoundingClientRect().bottom+offset<=(window.innerHeight||document.documentElement.clientHeight);}
function updateURLParameter(url,param,paramVal){let newAdditionalURL='',tempArray=url.split('?'),temp='';const baseURL=tempArray[0],additionalURL=tempArray[1];if(additionalURL){tempArray=additionalURL.split('&');for(let i=0;i<tempArray.length;i++){if(tempArray[i].split('=')[0]!=param){newAdditionalURL+=temp+tempArray[i];temp='&';}}}
const rows_txt=temp+''+param+'='+paramVal;return baseURL+'?'+newAdditionalURL+rows_txt;}
function percent(value,total){return Math.round((value / total)*100);}
function fail(reason,ErrorConstructor=Error){throw new ErrorConstructor(reason);}
function getExtension(theUrl){let theExt=theUrl.substr(theUrl.lastIndexOf('.')+1);if(theExt.indexOf('?')>-1){theExt=theExt.substr(0,theExt.indexOf('?'));}
return theExt;}
function getHash(theUrl){let theHash=theUrl.substr(theUrl.lastIndexOf('#'));if(theHash.indexOf('?')>-1){theHash=theHash.substr(0,theHash.indexOf('?'));}
return theHash;}
function ucFirst(str){return`${str.charAt(0).toUpperCase()}${str.slice(1)}`;}
function ensureFinalDot(str){str=str.replace(/^\s+|\s+$/g,'');if(str.length>0&&!str.endsWith('.')&&!str.endsWith('?')&&!str.endsWith('!')){str+='.';}
return str;}
function stripTags(str){const text=new DOMParser().parseFromString(str,'text/html');return text.body.textContent||'';}
function slugify(str){str=str.toLowerCase();str=str.normalize('NFD').replace(/[\u0300-\u036f]/g,'');str=str.replace(/[^-\w]+/g,'-').replace(/^-+|-+$/g,'');return str==''?'n-a':str;}
function generateid(str){str=slugify(str);return str.replace(/^[-\d]*/,'');}
var decodeEntities=(function(){var element=document.createElement('div');function decodeHTMLEntities(str){if(str&&typeof str==='string'){str=str.replace(/<script[^>]*>([\S\s]*?)<\/script>/gim,'');str=str.replace(/<\/?\w(?:[^"'>]|"[^"]*"|'[^']*')*>/gim,'');element.innerHTML=str;str=element.textContent;element.textContent='';}
return str;}
return decodeHTMLEntities;})();Array.prototype.max=function(){if(this.length==0)return undefined;let n=Number(this[0]);for(let i=1;i<this.length;i++){n=Math.max(n,this[i]);}
return n;};Array.prototype.min=function(){if(this.length==0)return undefined;let n=Number(this[0]);for(let i=1;i<this.length;i++){n=Math.min(n,this[i]);}
return n;};function countOccurrences(arr,value){return arr.reduce((a,v)=>(v===value?a+1:a),0);}
function extractKey(objs,key){return objs.map((obj)=>obj[key]);}
function sendForm(theForm,theAction,theTarget,theMethod){if(theAction!=null){document.forms[theForm].action=theAction;}
if(theTarget!=null){document.forms[theForm].target=theTarget;}
if(theMethod!=null){document.forms[theForm].method=theMethod;}
document.forms[theForm].submit();}
function checkBoxes(theForm,doCheck){const elts=document.forms[theForm].elements;for(let i=0;i<elts.length;i++){elts[i].checked=doCheck;}}
function checkBox(theForm,theName){const elt=document.forms[theForm].elements[theName];elt.checked=!elt.checked;}
function checkRadio(theId){document.getElementById(theId).checked=true;}
